### ISSUE TITLE
Несколько вопросов по схеме

### ISSUE THREAD

**Issue by Anonym-tsk** [Metori/mqtt_domofon#3]
Привет. Спасибо за отличное устройство. Есть несколько вопросов:
1. Будет работать с любым домофоном? У меня кажется Cyfral, не будет проблем?
2. Какие-то конкретные реле можете посоветовать?
3. По схеме не совсем понятно, куда уходит GND от светодиодов и от реле? Насколько я понял, от светодиодов уходит на GND NodeMCU, питание реле оттуда же. А вот GPIO12 через резистор и COM реле открытия к минусу линии домофона?
4. Будет ли корректно работать параллельно с трубкой домофона? Если я отвечу и открою дверь с трубки, устройство это поймет?
5. Не нужна ли оптопара для определения входящего звонка?

**Comment by Metori** [comment]
Привет.
1. Будет работать с любым аналоговым домофоном, но нужно подбирать сопротивления.
2. я использовал noname реле-модули для ардуино. думаю подойдут любые.
3. GND общее везде ж.
4. параллельно с трубкой не проверял. думаю, что могут возникнуть проблемы. проще просто реле подпаять к кнопкам трубки.
5. работает и с делителем.
